name: Build Docker Image and Transfer to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-transfer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # New step: Read version from package.json
      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t math-game:latest -t math-game:${{ steps.package-version.outputs.version }} .

      # Step 3: Save the Docker image as a tar file
      - name: Save Docker image
        run: |
          docker save math-game:latest math-game:${{ steps.package-version.outputs.version }} -o /tmp/math-game.tar
          chmod 644 /tmp/math-game.tar
          cp /tmp/math-game.tar .
          ls -al .

      # Step 4: Transfer the Docker image to the remote server
      - name: Transfer Docker image to server
        uses: easingthemes/ssh-deploy@v5.1.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          SOURCE: "math-game.tar"
          TARGET: "/home/deploy/"

      # Step 5: Load the Docker image on the server
      - name: Load Docker image on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          script: |
            docker stop math-game
            docker rm math-game
            docker load -i ~/math-game.tar
            docker run -d --name math-game -p 5007:80 --restart unless-stopped math-game:${{ steps.package-version.outputs.version }}
            rm ~/math-game.tar  # Optionally remove the tar file after loading
